export const sampleFarms = [
  {
    id: "1",
    name: "Sunshine Farm",
    address: "Somewhere 23",
    city: "Berlin",
    country: "Germany",
    distance: "5km",
    phone: "123456789",
    email: "farmone@farmone.site",
    website: "farmone.site",
    products: ["tomatoes", "bananas", "apples"],
    image: require("../img/farms/farm-01.jpg")
  },
  {
    id: "2",
    name: "Happy Farmer",
    address: "Somewhere 23",
    city: "Berlin",
    country: "Germany",
    distance: "3.5km",
    phone: "123456789",
    email: "farmone@farmone.site",
    website: "farmone.site",
    products: ["cucumbers", "potatoes", "pears"],
    image: require("../img/farms/farm-02.jpg")
  },
  {
    id: "3",
    name: "Greensleeves",
    address: "Somewhere 23",
    city: "Berlin",
    country: "Germany",
    distance: "2km",
    phone: "123456789",
    email: "farmone@farmone.site",
    website: "farmone.site",
    products: ["onions", "turnips", "broccoli"],
    image: require("../img/farms/farm-03.jpg")
  },
  {
    id: "4",
    name: "Fresh & Green",
    address: "Somewhere 23",
    city: "Berlin",
    country: "Germany",
    distance: "500m",
    phone: "123456789",
    email: "farmone@farmone.site",
    website: "farmone.site",
    products: ["apples", "lettuces", "pineapples"],
    image: require("../img/farms/farm-04.jpg")
  },
  {
    id: "5",
    name: "Uncle George's Farm",
    address: "Somewhere 23",
    city: "Berlin",
    country: "Germany",
    distance: "1km",
    phone: "123456789",
    email: "farmone@farmone.site",
    website: "farmone.site",
    products: ["bell peppers", "cucumbers", "eggplants"],
    image: require("../img/farms/farm-05.jpg")
  },
  {
    id: "6",
    name: "Vegan Heaven",
    address: "Somewhere 23",
    city: "Berlin",
    country: "Germany",
    distance: "1km",
    phone: "123456789",
    email: "farmone@farmone.site",
    website: "farmone.site",
    products: ["cauliflowers", "Kale", "Edamame"],
    image: require("../img/farms/farm-06.jpg")
  },
  {
    id: "7",
    name: "McArthur's Valley",
    address: "Somewhere 23",
    city: "Berlin",
    country: "Germany",
    distance: "1km",
    phone: "123456789",
    email: "farmone@farmone.site",
    website: "farmone.site",
    products: ["garlics", "potatoes", "onions"],
    image: require("../img/farms/farm-07.jpg")
  },
  {
    id: "8",
    name: "Fruities",
    address: "Somewhere 23",
    city: "Berlin",
    country: "Germany",
    distance: "1km",
    phone: "123456789",
    email: "farmone@farmone.site",
    website: "farmone.site",
    products: ["oranges", "apples", "kiwis"],
    image: require("../img/farms/farm-08.jpg")
  },
  {
    id: "9",
    name: "The Real Farmville",
    address: "Somewhere 23",
    city: "Berlin",
    country: "Germany",
    distance: "1km",
    phone: "123456789",
    email: "farmone@farmone.site",
    website: "farmone.site",
    products: ["carrots", "potatoes", "tomatoes"],
    image: require("../img/farms/farm-09.jpg")
  },
  {
    id: "10",
    name: "Greenfield's barn",
    address: "Somewhere 23",
    city: "Berlin",
    country: "Germany",
    distance: "1km",
    phone: "123456789",
    email: "farmone@farmone.site",
    website: "farmone.site",
    products: ["lettuces", "cabbages", "Spinach"],
    image: require("../img/farms/farm-10.jpg")
  }
];
