export const sampleFarms = [
  {
    id: "1",
    name: "Sunshine Farm",
    address: "542 Travis Road",
    city: "Dexville",
    country: "UK",
    distance: "5km",
    phone: "+44 4586785426",
    email: "info@sunshinefarm.site",
    website: "sunshinefarm.site",
    products: ["tomatoes", "bananas", "apples"],
    image: require("../img/farms/farm-01.jpg")
  },
  {
    id: "2",
    name: "Happy Farmer",
    address: "73 St. Peter's Street",
    city: "Preston",
    country: "UK",
    distance: "3.5km",
    phone: "+44 1226547895",
    email: "info@happyfarmer.site",
    website: "happyfarmer.site",
    products: ["cucumbers", "potatoes", "pears"],
    image: require("../img/farms/farm-02.jpg")
  },
  {
    id: "3",
    name: "Greensleeves",
    address: "Harbor's End",
    city: "Heartville",
    country: "UK",
    distance: "2km",
    phone: "+44 5684257895",
    email: "info@greensleeves.site",
    website: "greensleeves.site",
    products: ["onions", "turnips", "broccoli"],
    image: require("../img/farms/farm-03.jpg")
  },
  {
    id: "4",
    name: "Fresh & Green",
    address: "423 Brick Road",
    city: "New Boston",
    country: "UK",
    distance: "500m",
    phone: "+44 2564785425",
    email: "info@freshngreen.site",
    website: "freshngreen.site",
    products: ["apples", "lettuces", "pineapples"],
    image: require("../img/farms/farm-04.jpg")
  },
  {
    id: "5",
    name: "Uncle George's Farm",
    address: "34 National Road",
    city: "Luton Town",
    country: "UK",
    distance: "1km",
    phone: "+44 5642489545",
    email: "info@unclegeorgesfarm.site",
    website: "unclegeorgesfarm.site",
    products: ["bell peppers", "cucumbers", "eggplants"],
    image: require("../img/farms/farm-05.jpg")
  },
  {
    id: "6",
    name: "Vegan Heaven",
    address: "New Avenue's End",
    city: "Chester Town",
    country: "UK",
    distance: "1km",
    phone: "+44 5648525487",
    email: "info@veganheaven.site",
    website: "veganheaven.site",
    products: ["cauliflowers", "Kale", "Edamame"],
    image: require("../img/farms/farm-06.jpg")
  },
  {
    id: "7",
    name: "McArthur's Valley",
    address: "158 St. Jacob's Street",
    city: "Bradfordshire",
    country: "UK",
    distance: "1km",
    phone: "+44 5424856789",
    email: "info@mcarthursvalley.site",
    website: "mcarthursvalley.site",
    products: ["garlics", "potatoes", "onions"],
    image: require("../img/farms/farm-07.jpg")
  },
  {
    id: "8",
    name: "Fruities",
    address: "354 Broker's Road",
    city: "Oxfordville",
    country: "UK",
    distance: "1km",
    phone: "+44 1245789548",
    email: "info@fruities.site",
    website: "fruities.site",
    products: ["oranges", "apples", "kiwis"],
    image: require("../img/farms/farm-08.jpg")
  },
  {
    id: "9",
    name: "The Real Farmville",
    address: "12 Cardiff Avenue",
    city: "New Hope Town",
    country: "UK",
    distance: "1km",
    phone: "+44 5648754125",
    email: "info@therealfarmville.site",
    website: "therealfarmville.site",
    products: ["carrots", "potatoes", "tomatoes"],
    image: require("../img/farms/farm-09.jpg")
  },
  {
    id: "10",
    name: "Greenfield's Βarn",
    address: "347 Carfax Road",
    city: "Carfax City",
    country: "UK",
    distance: "1km",
    phone: "+44 5648524789",
    email: "info@greenfieldsbarn.site",
    website: "greenfieldsbarn.site",
    products: ["lettuces", "cabbages", "Spinach"],
    image: require("../img/farms/farm-10.jpg")
  }
];
